language: python
python:
  - "3.6"
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - source setup.sh
script:
  - coverage run --source=pictools setup.py test
  - make -C programmer/tst -s -j $(cat /proc/cpuinfo | grep processor | wc -l) test
after_success:
  coveralls
